### PR TITLE
Added new Kubernetes Tutorial

### PR DESCRIPTION
**Pull request by mariuszmichalowski**
**What this PR does / why we need it**:

Recently published Kubernetes Tutorial for beginners

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @your-reviewer

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ddysher** [comment]
thx!
/approve

**Review by gaocegege — APPROVED** [review]
/lgtm

**Comment by bbbmj** [comment]
Maybe @caicloud-bot  is not online, manual merge!

**Pull request merged**
